apiVersion: v1
kind: Service
metadata:
  name: kafka-webview
spec:
  selector:
    app: kafka-webview
  ports:
    - name: https
      port: 8443
      targetPort: https
    - name: metrics
      port: 9090
      targetPort: metrics
