apiVersion: v1
kind: Service
metadata:
  name: kafka-webview
spec:
  selector:
    app: kafka-webview
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: metrics
      port: 9090
      targetPort: metrics
